# Author: Ruzsa "RuzGer" Gergely Gábor
# API test file for itemizer-backend

# Get all category
GET {{dev-server}}/index.php/category
api-key: {{api-key}}

###

# Get one specified category
GET {{dev-server}}/index.php/category/{{category-id}}
api-key: {{api-key}}

###

# Get all item
GET {{dev-server}}/index.php/item
api-key: {{api-key}}

###

# Get one specified item
GET {{dev-server}}/index.php/item/{{item-id}}
api-key: {{api-key}}

###

# Create a category
POST {{dev-server}}/index.php/category
api-key: {{api-key}}
Content-Type: application/json

{
"name": "{{new-category-name}}"
}

###

# Create an item
POST {{dev-server}}/index.php/item
api-key: {{api-key}}
Content-Type: application/json

{
  "category": {{new-item-category}},
  "name": "{{new-item-name}}",
  "qty": {{new-item-qty}},
  "note": "{{new-item-note}}",
  "out_of_storage": {{new-item-oos}}
}

###

# Delete a category
DELETE {{dev-server}}/index.php/category/{{category-to-delete}}
api-key: {{api-key}}

###

# Delete an item
DELETE {{dev-server}}/index.php/item/{{item-to-delete}}
api-key: {{api-key}}

###

# Update an item
PUT {{dev-server}}/index.php/item/{{item-id}}
api-key: {{api-key}}
Content-Type: application/json

{
  "category": {{update-item-category}},
  "name": "{{update-item-name}}",
  "qty": {{update-item-qty}},
  "note": "{{update-item-note}}",
  "out_of_storage": {{update-item-oos}}
}

###

# Update a category
PUT {{dev-server}}/index.php/category/{{category-id}}
api-key: {{api-key}}
Content-Type: application/json

{
  "category": "{{update-category-name}}"
}

###